name: ExcludonFinder
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  # Core dependencies
  - r-base=4.1
  
  # Alignment tools
  - bwa-mem2=2.2.1
  - minimap2=2.24
  - samtools=1.15
  
  # Read counting and processing
  - subread=2.0.1
  
  # R packages for data manipulation
  - r-dplyr=1.0.7
  - r-foreach=1.5.2
  - r-doparallel=1.0.17
  - r-data.table=1.14
  
  # Bioconductor packages
  - r-biocmanager=1.30.19
  - bioconductor-rtracklayer=1.54.0
  
  # For parallel processing
  - r-iterators=1.0.13
  
  # System utilities
  - bc=1.07.1
  - gawk=5.1.0
  - sed=4.8
  
  # Development tools
  - git=2.34.1
  
  # Pipeline management
  - parallel=20211022
